#!/usr/bin/env python
# encoding: utf-8

import pylab
import numpy as np

import menpo.io as mio
from menpo.visualize.viewmatplotlib import _set_axes_options

from trafficsignrecognition import load_pretrained_model


def main(image_path):
    # load pre-trained model
    classifier = load_pretrained_model()
    # import image
    im = mio.import_image(image_path)
    # fit model
    result = classifier.fit(im)
    # visualize result
    pylab.imshow(im.pixels_with_channels_at_back())
    pylab.title(result.__str__())
    if result.bbox is not None:
        pylab.plot(result.bbox.points[:, 1], result.bbox.points[:, 0], 'r-', linewidth=4)
        pylab.plot([result.bbox.points[0, 1], result.bbox.points[3, 1]],
                   [result.bbox.points[0, 0], result.bbox.points[3, 0]], 'r-', linewidth=4)
        _set_axes_options(pylab.gca(), render_axes=False, inverted_y_axis=True, axes_x_limits=(0, im.width - 1),
                          axes_y_limits=(0, im.height - 1))
    pylab.show()


if __name__ == "__main__":
    from argparse import ArgumentParser

    parser = ArgumentParser(description="Traffic Sign Classification")
    parser.add_argument("image_path", help="Path to image file.")
    ns = parser.parse_args()
    main(ns.image_path)